[package]
name = "libgpg-error-sys"
version = "0.2.0"
authors = ["John Schug <john.ips.schug@gmail.com>"]
description = "Raw bindings for libgpg-error"
repository = "https://github.com/johnschug/rust-gpg-error"
license = "LGPL-2.1"
keywords = ["gpg"]
categories = ["external-ffi-bindings"]
links = "gpg-error"
build = "build.rs"

[lib]
name = "libgpg_error_sys"
path = "lib.rs"

[build-dependencies]
gcc = "0.3"
